#ifndef PLANTSPEAK_PIN_CONFIG_H
#define PLANTSPEAK_PIN_CONFIG_H

#define PLANTSPEAK_PIN_RED_USER_LED "P0_5"
#define PLANTSPEAK_PIN_GREEN_USER_LED "P0_11"
#define PLANTSPEAK_PIN_USER_PUSH_BUTTON "P0_10"
#define PLANTSPEAK_PIN_EN_PERIPHERALS "P0_6"
#define PLANTSPEAK_PIN_I2C_SCL "P0_8"
#define PLANTSPEAK_PIN_I2C_SDA "P0_9"

#endif
